### ISSUE TITLE
Django Community Blog Feed

### ISSUE THREAD

**Issue by adamchainz** [mchesler613/django_adventures#1]
Hi Merilyn,

You submitted your Django blog to the Django community blog posts feed (at https://www.djangoproject.com/community/ ). I've just approved it, so your new posts will come through!

Welcome aboard,

Adam

(I'm contacting you via GitHub issue since I couldn't find an email address anywhere.)

**Comment by mchesler613** [comment]
Thank you so much, @adamchainz !!
